<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IBM548-PC0GJ1ML" ignored="0" name="Sample test" tests="3" failures="1" timestamp="22 Jan 2019 10:50:57 GMT" time="90.645" errors="0">
  <testcase name="@AfterMethod tearDown" time="1.013" classname="com.training.functional.tests.RETC024AddNewUserTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.training.functional.tests.RETC024AddNewUserTest.tearDown(RETC024AddNewUserTest.java:65)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setUp" time="0.0" classname="com.training.functional.tests.RETC024AddNewUserTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="com.training.functional.tests.RETC024AddNewUserTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="validLoginTest" time="18.157" classname="com.training.functional.tests.LoginTests"/>
  <testcase name="validLoginTest" time="0.001" classname="com.training.functional.tests.LoginTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.training.functional.tests.LoginTests.validLoginTest(LoginTests.java:44)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
  <testcase name="createUserSub" time="0.0" classname="com.training.functional.tests.RETC024AddNewUserTest">
    <skipped/>
  </testcase> <!-- createUserSub -->
</testsuite> <!-- Sample test -->
